import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import StoreProvider from "./store/provider";
import { CryptoContextProvider } from "./context/context";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <CryptoContextProvider>
        <body className={inter.className}>
          <StoreProvider>{children}</StoreProvider>
        </body>
      </CryptoContextProvider>
    </html>
  );
}
