import "./globals.css";
import StoreProvider from "./store/provider";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { CryptoContextProvider } from "./context/context";
import { TopSection } from "./ui/TopSections";
import { TheThemeProvider } from "./ui/TheThemProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head></head>
      <body
        className={` bg-gray-100 dark:bg-gray-950 dark:text-gray-400 ${inter.className}`}
      >
        <TheThemeProvider>
          <CryptoContextProvider>
            <StoreProvider>
              <TopSection />
              {children}
            </StoreProvider>
          </CryptoContextProvider>
        </TheThemeProvider>
      </body>
    </html>
  );
}
